var AGENCIA = {
    'BOGN794':	"IM TRAVEL SAS",
    'CLON950':	"SERVIVUELOS",
    'IPIH217':	"VIAJES GUZMAN Y CIA LTDA",
    'IPIH720':	"VALENCIA TORRES LTDA",
    'IPIO151':	"COSTA Y MAR TRAVEL",
    'PSOH265':	"VIAJES LA GUANENA",
    'PSOH305':	"ELITURS SAS",
    'PSOM757':	"TURITUR",
    'PUUB711':	"SELVA VIAJES Y TURISMO",
}
